### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#313]
The every-24-hour script for the ML nodes takes 2 minutes and 25s to run on the sonar VM (which was otherwise not busy).  This is probably as bad as it's going to get since we have more than 3 months of data and the longest run generates a report for the last quarter.  At the same time, (a) that's quite a lot of time and (b) there will be many more clusters added.  Simple monitoring says that almost all the time is spent in sonalyze, not much in naicreport.  Let's enumerate some obvious avenues for better performance, based partly on profiling and partly on gut feeling.

- [ ] Caching of parsed and cleaned data, #161.  A lot of time is being spent reading the sonar data from unreliable CSV files
- [x] Parallelism internal to sonalyze might help - files can be read in parallel, at least
- [ ] Parallelism in merge_streams (see also #314) - if the timeline can be subdivided quickly (not necessarily easy!) then different threads can work on merging streams within those windows.
- [ ] Parallelism external to sonalyze (ie the quarterly and monthly reports might be generated at the same time) might help
- [x] A better-provisioned VM: Parallelism will require the VM to be provisioned with more CPU (it currently has one) and possibly with more memory; each invocation of the script requires more than 1GB resident memory, and this probably eats from anything that in-memory disk cache uses, and we don't want to do that
- [ ] Obviously, better algorithms in sonalyze, eg #314
- [x] A streams-based API towards the data store, #379, #386, so that we don't have to keep it all in memory
- [x] Memory management, #414.

**Comment by lars-t-hansen** [comment]
On my computer (which is *a lot* faster than the VM), perf says that 56% of the running time of the monthly report is spent in `merge_streams`, I've added #314.

**Comment by lars-t-hansen** [comment]
The new VM is quite a lot faster than the old VM, this takes a little bit of the edge off the problem.

**Comment by lars-t-hansen** [comment]
The VM has been upgraded to 32GB RAM, which helps a lot for large analysis jobs.

**Comment by lars-t-hansen** [comment]
CSV parsing and data representation have been changed in major ways, leading to more than 2x perf improvement and a 50% reduction in peak memory use (and a 95% reduction in allocation volume).

**Comment by lars-t-hansen** [comment]
Having probed this further with Samply, it's clear that for most `sonalyze jobs` workloads the time is being spent reading the database: easily 50% of the time, actually.  Most of that time is spent parsing CSV and converting.  That parser is pretty well optimized, and though more can be done around the edges the only thing that's really going to move the needle is to cache the parsed data and read the cached data, bypassing parsing, checking, and conversion altogether.  I expect about 80% of those 50% to simply disappear if we do this.

However, most `sonalyze jobs` runs will be for near-term data, where there isn't that much data to read, and where performance is not all that important.

For `sonalyze load`, the running time is dominated by the quadratic stream merging, but this is not tremendously problematic because that feature is being used mostly by reports that are generated in the background for later consumption.  Also the generation happens when the system is not going to have many interactive users.

And `sonalyze uptime` is similar to `load`, and `sonalyze profile` is similar to `jobs`.

I think in conclusion, we should look into caching when we look at #379 and the quadratic merge algorithm needs to be fixed at some point, but there's nothing critical about performance at this point.

**Comment by lars-t-hansen** [comment]
With the transition to the Go version of sonalyze, I've made file reading concurrent and it's generally much faster than the Rust version.  What remains here is to fix the quadratic algorithm and (maybe) add caching.  I'll close this bug as fixed, and let those bugs stand on their own.  I see no point in worrying about parallel report generation at this point, it'll just create contention on the server.
